#include "ply_export.hpp"
#include <cstdio>
#include <cmath>
#include <algorithm>

namespace da {

bool write_gaussian_ply(const std::string& path, const Gaussians& g) {
    const int N = g.N;
    if (N <= 0) return false;
    if ((int)g.means.size()!=N*3 || (int)g.scales.size()!=N*3 ||
        (int)g.rotations.size()!=N*4 || (int)g.opacities.size()!=N ||
        (int)g.harmonics.size()!=N*3*9) return false;

    std::FILE* f = std::fopen(path.c_str(), "wb");
    if (!f) return false;

    std::fprintf(f, "ply\n");
    std::fprintf(f, "format binary_little_endian 1.0\n");
    std::fprintf(f, "comment generated by depth-anything.cpp (DA3 gaussians)\n");
    std::fprintf(f, "element vertex %d\n", N);
    std::fprintf(f, "property float x\nproperty float y\nproperty float z\n");
    std::fprintf(f, "property float f_dc_0\nproperty float f_dc_1\nproperty float f_dc_2\n");
    std::fprintf(f, "property float opacity\n");
    std::fprintf(f, "property float scale_0\nproperty float scale_1\nproperty float scale_2\n");
    std::fprintf(f, "property float rot_0\nproperty float rot_1\nproperty float rot_2\nproperty float rot_3\n");
    std::fprintf(f, "end_header\n");

    bool ok = true;
    for (int i = 0; i < N && ok; ++i) {
        float rec[14];
        rec[0]=g.means[i*3+0]; rec[1]=g.means[i*3+1]; rec[2]=g.means[i*3+2];
        // f_dc = SH DC coefficient (coeff 0) per color channel.
        rec[3]=g.harmonics[(i*3+0)*9+0];
        rec[4]=g.harmonics[(i*3+1)*9+0];
        rec[5]=g.harmonics[(i*3+2)*9+0];
        // opacity stored as logit (inverse sigmoid).
        float op = std::min(1.0f-1e-6f, std::max(1e-6f, g.opacities[i]));
        rec[6]=std::log(op/(1.0f-op));
        // scales stored as log.
        for (int d=0; d<3; ++d){ float sc=std::max(1e-9f, g.scales[i*3+d]); rec[7+d]=std::log(sc); }
        // rotation wxyz (already wxyz).
        rec[10]=g.rotations[i*4+0]; rec[11]=g.rotations[i*4+1];
        rec[12]=g.rotations[i*4+2]; rec[13]=g.rotations[i*4+3];
        ok = std::fwrite(rec, sizeof(float), 14, f) == 14;
    }
    std::fclose(f);
    return ok;
}

} // namespace da
